version: 2
updates:
- package-ecosystem: nuget
  directory: "/Synethia/Synethia.App"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - Leo-Peyronnet
  assignees:
  - Leo-Peyronnet
